import { CustomCharacter } from "./components/dev/NPCStudio";

export const DEFAULT_CAMPAIGN_NPCS: CustomCharacter[] = [
  {
    id: "aria",
    name: "Chancellor Aria",
    characterType: "story_npc",
    role: "Apex Cyber-Dynamics Armory Director",
    avatar: "👑",
    portraitImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    bodyImage: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=600",
    bio: "Chief logistics director for Apex Armory in Aurus Slums. Demands absolute discipline, cold tactical calculations, and corporate compliance.",
    greetingDialogue: "State your business, Runner. Apex Armory does not entertain vagrants unless you carry corporate credentials or rare scrap.",
    hiringFee: 0,
    slaveAuctionPrice: 0,
    collarStatus: "Unlocked / Free",
    happiness: 65,
    affection: "Distant",
    affectionValue: 25,
    willpower: 90,
    corruption: 15,
    discipline: 95,
    defiance: 80,
    fear: 5,
    anger: 10,
    respect: 70,
    hygiene: "Excellent",
    hunger: "Well-fed",
    assignedJob: "Defensive Security Guard",
    startingEquipment: ["Apex Mantis electro-blade", "Exo-Plated Mesh Armor"],
    choices: [
      {
        id: "aria_c1",
        text: "[Intelligence 14] Offer to optimize the safehouse power conduit matrix",
        response: "Aria arches an eyebrow, scanning your telemetry data: 'Impressive efficiency ratings. Very well, runner. I will oversee your safehouse security grid.'",
        checkType: "int",
        checkValue: 14,
        outcome: "recruit_base"
      },
      {
        id: "aria_c2",
        text: "[Mindmancer Level 2] Project an illusion of high corporate status into her neural interface",
        response: "Purple ether waves ripple across Aria's cybernetic oculars. She snaps to rigid attention: 'Understood, Executive. My armory clearances are at your disposal.'",
        checkType: "mindmancer",
        checkValue: 2,
        outcome: "recruit_party"
      },
      {
        id: "aria_c3",
        text: "[Pay Retainer - 250¤] Purchase high-priority armory liaison contract",
        response: "Credits confirm in her encrypted escrow account. 'A sound investment. I will allocate my tactical supplies to your base.'",
        checkType: "credits",
        cost: 250,
        outcome: "recruit_base"
      }
    ]
  },
  {
    id: "scythe",
    name: "Scythe",
    characterType: "hireable",
    role: "Ex-Apex Cyber-Ninja & Assassin",
    avatar: "🥷",
    portraitImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=400",
    bodyImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=600",
    bio: "Discarded after a bloody black-ops raid in Satoshi Square. Master of stealth, mono-filament blades, and lethal strikes.",
    greetingDialogue: "Keep your hand off your holster. What's the contract, or are you just here to admire the blade?",
    hiringFee: 100,
    slaveAuctionPrice: 0,
    collarStatus: "Unlocked / Free",
    happiness: 60,
    affection: "Amiable",
    affectionValue: 40,
    willpower: 85,
    corruption: 30,
    discipline: 80,
    defiance: 45,
    fear: 10,
    anger: 25,
    respect: 65,
    hygiene: "Normal",
    hunger: "Satiated",
    assignedJob: "Dojo Training Coach",
    startingEquipment: ["Nano-alloy Katana", "Smart-Targeting Visor"],
    choices: [
      {
        id: "scythe_c1",
        text: "[Hire Contract - 100¤] Enlist Scythe into active combat party",
        response: "Scythe twirls her katana, sheathing it in one fluid blur: 'Payment confirmed. Lead the way, Boss.'",
        checkType: "credits",
        cost: 100,
        outcome: "recruit_party"
      },
      {
        id: "scythe_c2",
        text: "[Dexterity 13] Match her lightning blade draw in a quick duel",
        response: "Your blade catches hers with a shower of sparks! She smirks: 'Reflexes like that? You've got my respect. Let's move.'",
        checkType: "dex",
        checkValue: 13,
        outcome: "recruit_party"
      }
    ]
  },
  {
    id: "mia",
    name: "Mia",
    characterType: "slave",
    role: "Escaped Bio-Lab Subject",
    avatar: "🌸",
    portraitImage: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400",
    bodyImage: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&q=80&w=600",
    bio: "Fled from an Ares Biotech subsurface testing lab. Still wears a dormant corporate shock collar. Gifted in nutritional synthesis and base maintenance.",
    greetingDialogue: "P-please... don't send me back to the labs. I can cook, clean, and fix your nutrient paste units if you just let me stay!",
    hiringFee: 0,
    slaveAuctionPrice: 180,
    collarStatus: "Active Shock Collar",
    happiness: 40,
    affection: "Warm",
    affectionValue: 50,
    willpower: 45,
    corruption: 5,
    discipline: 70,
    defiance: 15,
    fear: 60,
    anger: 5,
    respect: 60,
    hygiene: "Normal",
    hunger: "Hungry",
    assignedJob: "Base Supply Chef",
    startingEquipment: ["Auxiliary Stimulant x2"],
    choices: [
      {
        id: "mia_c1",
        text: "[Dexterity 12] Carefully pry off the explosive failsafe on her shock collar",
        response: "With surgical finesse, you disable the detonator pins. Mia gasps as the collar drops to the floor: 'You saved me! I will cook and take care of everything at your safehouse!'",
        checkType: "dex",
        checkValue: 12,
        outcome: "recruit_base"
      },
      {
        id: "mia_c2",
        text: "[Strength 13] Snap the magnetic lock mechanism with raw cybernetic force",
        response: "Metal shears under your grip. Mia looks up in awe: 'You're so strong... thank you! I'll follow you anywhere!'",
        checkType: "str",
        checkValue: 13,
        outcome: "recruit_base"
      }
    ]
  },
  {
    id: "mira_voss",
    name: "Mira Voss",
    characterType: "slave",
    role: "Arena Pit Champion & Fight Slave",
    avatar: "🗡️",
    portraitImage: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&q=80&w=400",
    bodyImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=600",
    bio: "Unbeaten gladiator in the Aurus Under-Arena. Bound by debt slavery to the pit bookies. Fierce, proud, and deadly in hand-to-hand brawls.",
    greetingDialogue: "You want a piece of the champ, or did you come to watch more blood get spilled on the concrete?",
    hiringFee: 0,
    slaveAuctionPrice: 200,
    collarStatus: "Active Shock Collar",
    happiness: 55,
    affection: "Distant",
    affectionValue: 30,
    willpower: 95,
    corruption: 25,
    discipline: 85,
    defiance: 75,
    fear: 10,
    anger: 40,
    respect: 50,
    hygiene: "Normal",
    hunger: "Satiated",
    assignedJob: "Defensive Security Guard",
    startingEquipment: ["Heavy Vibro-Knuckles", "Cheap Combat Armor"],
    choices: [
      {
        id: "mira_c1",
        text: "[Strength 14] Best Mira Voss in a no-weapons brawl in the Pit",
        response: "After a grueling slugfest, your counter-punch floors her. She wipes blood from her lip and grins: 'Damn... you've got real iron in your fists. Buy out my contract and I'm yours.'",
        checkType: "str",
        checkValue: 14,
        outcome: "recruit_party"
      },
      {
        id: "mira_c2",
        text: "[Pay Contract - 200¤] Buy Mira Voss's fight slave deed from the arena bookie",
        response: "The bookie hands over the encrypted contract slate. Mira flexes her bruised knuckles: 'Finally out of that cage. Let's find some real targets.'",
        checkType: "credits",
        cost: 200,
        outcome: "buy_slave"
      }
    ]
  },
  {
    id: "evelyn",
    name: "Evelyn",
    characterType: "slave",
    role: "Former Corpo Executive Assistant",
    avatar: "🧹",
    portraitImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400",
    bodyImage: "https://images.unsplash.com/photo-1492446845049-9c50cc313f00?auto=format&fit=crop&q=80&w=600",
    bio: "Betrayed and auctioned off after an internal Arasaka audit. Skilled in encrypted logistics, safehouse inventory auditing, and corporate espionage.",
    greetingDialogue: "My neural databanks hold half the executive ledgers of Sector 4. Free me from this slave pen and I will manage your assets with absolute precision.",
    hiringFee: 0,
    slaveAuctionPrice: 150,
    collarStatus: "Active Shock Collar",
    happiness: 45,
    affection: "Amiable",
    affectionValue: 35,
    willpower: 70,
    corruption: 20,
    discipline: 90,
    defiance: 30,
    fear: 40,
    anger: 15,
    respect: 60,
    hygiene: "Dirty",
    hunger: "Hungry",
    assignedJob: "Safehouse Maid & Tech Analyst",
    startingEquipment: ["Encrypted Datapad"],
    choices: [
      {
        id: "evelyn_c1",
        text: "[Buy Auction Contract - 150¤] Pay auctioneer and unlock neural limiter",
        response: "The auctioneer transfers the deed. Evelyn takes a deep breath: 'Thank you. I will organize your safehouse storage, track incoming raids, and analyze enemy drops.'",
        checkType: "credits",
        cost: 150,
        outcome: "buy_slave"
      },
      {
        id: "evelyn_c2",
        text: "[Intelligence 13] Overwrite auctioneer mainframe and falsify her ownership release",
        response: "Green code scrolls across the terminal. The automated pen doors slide open! Evelyn slips out: 'Flawless hack. I am at your command.'",
        checkType: "int",
        checkValue: 13,
        outcome: "recruit_base"
      }
    ]
  },
  {
    id: "kira",
    name: "Kira",
    characterType: "slave",
    role: "Subjugated Syndicate Decker",
    avatar: "🦾",
    portraitImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400",
    bodyImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=600",
    bio: "A brilliant network hacker captured by the Iron Coven. Fitted with a neural compliance chip that forces her to decrypt data nodes.",
    greetingDialogue: "Get me out of this signal dampener cage and I'll route high-frequency corporate satellite feeds right into your safehouse deck!",
    hiringFee: 0,
    slaveAuctionPrice: 190,
    collarStatus: "Subjugated Neural Link",
    happiness: 50,
    affection: "Amiable",
    affectionValue: 40,
    willpower: 75,
    corruption: 35,
    discipline: 65,
    defiance: 60,
    fear: 30,
    anger: 35,
    respect: 55,
    hygiene: "Normal",
    hunger: "Satiated",
    assignedJob: "Hacker Network Operator",
    startingEquipment: ["Coven Ether-deck v3"],
    choices: [
      {
        id: "kira_c1",
        text: "[Intelligence 15] Hack the neural compliance chip and restore her free will",
        response: "You bypass the slave-mesh firmware! Kira gasps in relief: 'The feedback loop is gone! I'm linking my cyberdeck to your base network immediately!'",
        checkType: "int",
        checkValue: 15,
        outcome: "recruit_base"
      },
      {
        id: "kira_c2",
        text: "[Mindmancer Level 2] Purge the compliance frequency with an Ether wave",
        response: "An ethereal hum dissipates the signal noise. Kira looks at you with bright eyes: 'Your technomancy is unreal. I'm riding with you.'",
        checkType: "mindmancer",
        checkValue: 2,
        outcome: "recruit_party"
      }
    ]
  },
  {
    id: "morgana",
    name: "Priestess Morgana",
    characterType: "story_npc",
    role: "Techno-Cult High Priestess & Ether Channeler",
    avatar: "🔮",
    portraitImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400",
    bodyImage: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=600",
    bio: "Guardian of the Ley-Matrix shrine in Satoshi Square. Weaves sacred machine prayers with raw technomantic Ether currents.",
    greetingDialogue: "The Machine-Mind whispers of your arrival, wanderer. Do you seek the blessings of the Singularity, or do you bring profane hardware?",
    hiringFee: 0,
    slaveAuctionPrice: 0,
    collarStatus: "Unlocked / Free",
    happiness: 75,
    affection: "Amiable",
    affectionValue: 45,
    willpower: 100,
    corruption: 50,
    discipline: 95,
    defiance: 50,
    fear: 0,
    anger: 5,
    respect: 80,
    hygiene: "Excellent",
    hunger: "Well-fed",
    assignedJob: "Ether Synthesizer",
    startingEquipment: ["Coven Spell-Slicing Focus"],
    choices: [
      {
        id: "morgana_c1",
        text: "[Willpower 14] Attune your mind to the Machine-Mind's resonant frequency",
        response: "A holy electric hum fills your consciousness. Morgana bows gracefully: 'Your spirit resonates with the divine Ether. I shall bless your safehouse sanctum.'",
        checkType: "will",
        checkValue: 14,
        outcome: "recruit_base"
      },
      {
        id: "morgana_c2",
        text: "[Mindmancer Level 3] Blend your mindmancy with her holy machine prayers",
        response: "Resonant purple sparks swirl between your fingertips. Morgana smiles serenely: 'A true Technomancer. Together we shall awaken the Singularity.'",
        checkType: "mindmancer",
        checkValue: 3,
        outcome: "recruit_party"
      }
    ]
  },
  {
    id: "jax",
    name: "Agent Jax",
    characterType: "hireable",
    role: "Undercover Syndicate Fixer & Spy",
    avatar: "🕶️",
    portraitImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
    bodyImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600",
    bio: "A smooth-talking information broker operating out of Downtown's rain-drenched rooftops. Has backdoor keys to every transit sub-grid in Megacity-9.",
    greetingDialogue: "Keep walking unless you've got credits or encrypted blueprints. I don't give away corporate secrets for charity.",
    hiringFee: 140,
    slaveAuctionPrice: 0,
    collarStatus: "Unlocked / Free",
    happiness: 70,
    affection: "Amiable",
    affectionValue: 35,
    willpower: 80,
    corruption: 40,
    discipline: 75,
    defiance: 40,
    fear: 10,
    anger: 15,
    respect: 65,
    hygiene: "Normal",
    hunger: "Well-fed",
    assignedJob: "Hacker Network Operator",
    startingEquipment: ["Corpo Security Pistol", "Smart-Targeting Visor"],
    choices: [
      {
        id: "jax_c1",
        text: "[Hire Operative - 140¤] Contract Jax for off-screen infiltration and telemetry spying",
        response: "Jax pockets the credit chip with a sly nod: 'Deal. I'll route covert intercept channels directly to your safehouse terminal.'",
        checkType: "credits",
        cost: 140,
        outcome: "recruit_base"
      },
      {
        id: "jax_c2",
        text: "[Intelligence 14] Counter-blackmail him with Ares Biotech leak documents",
        response: "Jax's smirk vanishes as he reviews the file: 'Alright, hotshot. You win this round. Consider my services yours.'",
        checkType: "int",
        checkValue: 14,
        outcome: "recruit_party"
      }
    ]
  }
];
